ModuleInfo "Version: 0.52"
ModuleInfo "Main Author: Simon Harrison (simonh@blitzbasic.com). Includes routines by various authors."
ModuleInfo "License: You are free to use this code as you please"
ModuleInfo "Please see readme.txt for more details"
import brl.blitz
import brl.glmax2d
import pub.glew
import brl.bmploader
import brl.pngloader
import brl.jpgloader
import brl.retro
TGlobal^Object{
width%&=mem("_sidesign_minib3d_TGlobal_width")
height%&=mem("_sidesign_minib3d_TGlobal_height")
mode%&=mem("_sidesign_minib3d_TGlobal_mode")
depth%&=mem("_sidesign_minib3d_TGlobal_depth")
rate%&=mem("_sidesign_minib3d_TGlobal_rate")
ambient_red#&=mem:f("_sidesign_minib3d_TGlobal_ambient_red")
ambient_green#&=mem:f("_sidesign_minib3d_TGlobal_ambient_green")
ambient_blue#&=mem:f("_sidesign_minib3d_TGlobal_ambient_blue")
vbo_enabled%&=mem("_sidesign_minib3d_TGlobal_vbo_enabled")
aa%&=mem("_sidesign_minib3d_TGlobal_aa")
ACSIZE%&=mem("_sidesign_minib3d_TGlobal_ACSIZE")
jitter%&=mem("_sidesign_minib3d_TGlobal_jitter")
j#&[,]&=mem:p("_sidesign_minib3d_TGlobal_j")
-New%()="_sidesign_minib3d_TGlobal_New"
-Delete%()="_sidesign_minib3d_TGlobal_Delete"
+Graphics3D%(w%,h%,d%=0,m%=0,r%=60,flags%=-1)="_sidesign_minib3d_TGlobal_Graphics3D"
+AntiAlias%(samples%)="_sidesign_minib3d_TGlobal_AntiAlias"
+Wireframe%(enable%)="_sidesign_minib3d_TGlobal_Wireframe"
+AmbientLight%(r#,g#,b#)="_sidesign_minib3d_TGlobal_AmbientLight"
+ClearCollisions%()="_sidesign_minib3d_TGlobal_ClearCollisions"
+Collisions%(src_no%,dest_no%,method_no%,response_no%=0)="_sidesign_minib3d_TGlobal_Collisions"
+ClearWorld%(entities%=1,brushes%=1,textures%=1)="_sidesign_minib3d_TGlobal_ClearWorld"
+UpdateWorld%(anim_speed#=1#)="_sidesign_minib3d_TGlobal_UpdateWorld"
+RenderWorld%()="_sidesign_minib3d_TGlobal_RenderWorld"
+RenderWorldAA%()="_sidesign_minib3d_TGlobal_RenderWorldAA"
+RenderCamera%(cam:TCamera)="_sidesign_minib3d_TGlobal_RenderCamera"
+AutoFade%(cam:TCamera,mesh:TMesh)="_sidesign_minib3d_TGlobal_AutoFade"
+GraphicsInit%()="_sidesign_minib3d_TGlobal_GraphicsInit"
+EnableStates%()="_sidesign_minib3d_TGlobal_EnableStates"
+RenderListAdd%(mesh:TMesh,List:TList)="_sidesign_minib3d_TGlobal_RenderListAdd"
+UpdateSprites%(cam:TCamera,list:TList)="_sidesign_minib3d_TGlobal_UpdateSprites"
}="sidesign_minib3d_TGlobal"
TEntity^Object{
entity_list:TList&=mem:p("_sidesign_minib3d_TEntity_entity_list")
tformed_x#&=mem:f("_sidesign_minib3d_TEntity_tformed_x")
tformed_y#&=mem:f("_sidesign_minib3d_TEntity_tformed_y")
tformed_z#&=mem:f("_sidesign_minib3d_TEntity_tformed_z")
.child_list:TList&
.parent:TEntity&
.mat:TMatrix&
.px#&
.py#&
.pz#&
.sx#&
.sy#&
.sz#&
.rx#&
.ry#&
.rz#&
.qw#&
.qx#&
.qy#&
.qz#&
.name$&
.class$&
.hide%&
.order%&
.alpha_order#&
.auto_fade%&
.fade_near#&
.fade_far#&
.fade_alpha#&
.brush:TBrush&
.cull_radius#&
.radius_x#&
.radius_y#&
.box_x#&
.box_y#&
.box_z#&
.box_w#&
.box_h#&
.box_d#&
.collision_type%&
.no_collisions%&
.collision:TCollisionImpact&[]&
.pick_mode%&
.obscurer%&
.anim%&
.anim_render%&
.anim_mode%&
.anim_time#&
.anim_speed#&
.anim_seq%&
.anim_trans%&
.anim_dir%&
.anim_seqs_first%&[]&
.anim_seqs_last%&[]&
.no_seqs%&
.anim_update%&
.old_x#&
.old_y#&
.old_z#&
.link:TLink&
-New%()="_sidesign_minib3d_TEntity_New"
-Delete%()="_sidesign_minib3d_TEntity_Delete"
-CopyEntity:TEntity(parent_ent:TEntity="bbNullObject")A="brl_blitz_NullMethodError"
-Update%()A="brl_blitz_NullMethodError"
-FreeEntity%()="_sidesign_minib3d_TEntity_FreeEntity"
-PositionEntity%(x#,y#,z#,glob%=0)="_sidesign_minib3d_TEntity_PositionEntity"
-MoveEntity%(mx#,my#,mz#)="_sidesign_minib3d_TEntity_MoveEntity"
-TranslateEntity%(tx#,ty#,tz#,glob%=0)="_sidesign_minib3d_TEntity_TranslateEntity"
-ScaleEntity%(x#,y#,z#,glob%=0)="_sidesign_minib3d_TEntity_ScaleEntity"
-RotateEntity%(x#,y#,z#,glob%=0)="_sidesign_minib3d_TEntity_RotateEntity"
-TurnEntity%(x#,y#,z#,glob%=0)="_sidesign_minib3d_TEntity_TurnEntity"
-PointEntity%(target_ent:TEntity,roll#=0#)="_sidesign_minib3d_TEntity_PointEntity"
-LoadAnimSeq%(file$)="_sidesign_minib3d_TEntity_LoadAnimSeq"
-ExtractAnimSeq%(first_frame%,last_frame%,seq%=0)="_sidesign_minib3d_TEntity_ExtractAnimSeq"
-Animate%(mode%=1,speed#=1#,seq%=0,trans%=0)="_sidesign_minib3d_TEntity_Animate"
-SetAnimTime%(time#,seq%=0)="_sidesign_minib3d_TEntity_SetAnimTime"
-AnimSeq%()="_sidesign_minib3d_TEntity_AnimSeq"
-AnimLength%()="_sidesign_minib3d_TEntity_AnimLength"
-AnimTime#()="_sidesign_minib3d_TEntity_AnimTime"
-Animating%()="_sidesign_minib3d_TEntity_Animating"
-EntityColor%(r#,g#,b#)="_sidesign_minib3d_TEntity_EntityColor"
-EntityAlpha%(a#)="_sidesign_minib3d_TEntity_EntityAlpha"
-EntityShininess%(s#)="_sidesign_minib3d_TEntity_EntityShininess"
-EntityTexture%(texture:TTexture,frame%=0,index%=0)="_sidesign_minib3d_TEntity_EntityTexture"
-EntityBlend%(blend_no%)="_sidesign_minib3d_TEntity_EntityBlend"
-EntityFX%(fx_no%)="_sidesign_minib3d_TEntity_EntityFX"
-EntityAutoFade%(near#,far#)="_sidesign_minib3d_TEntity_EntityAutoFade"
-PaintEntity%(bru:TBrush)="_sidesign_minib3d_TEntity_PaintEntity"
-EntityOrder%(order_no%)="_sidesign_minib3d_TEntity_EntityOrder"
-ShowEntity%()="_sidesign_minib3d_TEntity_ShowEntity"
-HideEntity%()="_sidesign_minib3d_TEntity_HideEntity"
-Hidden%()="_sidesign_minib3d_TEntity_Hidden"
-NameEntity%(e_name$)="_sidesign_minib3d_TEntity_NameEntity"
-EntityParent%(parent_ent:TEntity,glob%=1)="_sidesign_minib3d_TEntity_EntityParent"
-GetParent:TEntity()="_sidesign_minib3d_TEntity_GetParent"
-EntityX#(glob%=0)="_sidesign_minib3d_TEntity_EntityX"
-EntityY#(glob%=0)="_sidesign_minib3d_TEntity_EntityY"
-EntityZ#(glob%=0)="_sidesign_minib3d_TEntity_EntityZ"
-EntityPitch#(glob%=0)="_sidesign_minib3d_TEntity_EntityPitch"
-EntityYaw#(glob%=0)="_sidesign_minib3d_TEntity_EntityYaw"
-EntityRoll#(glob%=0)="_sidesign_minib3d_TEntity_EntityRoll"
-EntityClass$()="_sidesign_minib3d_TEntity_EntityClass"
-EntityName$()="_sidesign_minib3d_TEntity_EntityName"
-CountChildren%()="_sidesign_minib3d_TEntity_CountChildren"
-GetChild:TEntity(child_no%)="_sidesign_minib3d_TEntity_GetChild"
-FindChild:TEntity(child_name$)="_sidesign_minib3d_TEntity_FindChild"
-EntityPick:TEntity(range#)="_sidesign_minib3d_TEntity_EntityPick"
-LinePick:TEntity(x#,y#,z#,dx#,dy#,dz#,radius#=0#)="_sidesign_minib3d_TEntity_LinePick"
-EntityVisible%(src_entity:TEntity,dest_entity:TEntity)="_sidesign_minib3d_TEntity_EntityVisible"
-EntityDistance#(ent2:TEntity)="_sidesign_minib3d_TEntity_EntityDistance"
-DeltaYaw#(ent2:TEntity)="_sidesign_minib3d_TEntity_DeltaYaw"
-DeltaPitch#(ent2:TEntity)="_sidesign_minib3d_TEntity_DeltaPitch"
+TFormPoint%(x#,y#,z#,src_ent:TEntity,dest_ent:TEntity)="_sidesign_minib3d_TEntity_TFormPoint"
+TFormVector%(x#,y#,z#,src_ent:TEntity,dest_ent:TEntity)="_sidesign_minib3d_TEntity_TFormVector"
+TFormNormal%(x#,y#,z#,src_ent:TEntity,dest_ent:TEntity)="_sidesign_minib3d_TEntity_TFormNormal"
+TFormedX#()="_sidesign_minib3d_TEntity_TFormedX"
+TFormedY#()="_sidesign_minib3d_TEntity_TFormedY"
+TFormedZ#()="_sidesign_minib3d_TEntity_TFormedZ"
-GetMatElement#(row%,col%)="_sidesign_minib3d_TEntity_GetMatElement"
-ResetEntity%()="_sidesign_minib3d_TEntity_ResetEntity"
-EntityRadius%(rx#,ry#=0#)="_sidesign_minib3d_TEntity_EntityRadius"
-EntityBox%(x#,y#,z#,w#,h#,d#)="_sidesign_minib3d_TEntity_EntityBox"
-EntityType%(type_no%,recursive%=0)="_sidesign_minib3d_TEntity_EntityType"
-EntityPickMode%(no%,obscure%=1)="_sidesign_minib3d_TEntity_EntityPickMode"
-EntityCollided:TEntity(type_no%)="_sidesign_minib3d_TEntity_EntityCollided"
-CountCollisions%()="_sidesign_minib3d_TEntity_CountCollisions"
-CollisionX#(index%)="_sidesign_minib3d_TEntity_CollisionX"
-CollisionY#(index%)="_sidesign_minib3d_TEntity_CollisionY"
-CollisionZ#(index%)="_sidesign_minib3d_TEntity_CollisionZ"
-CollisionNX#(index%)="_sidesign_minib3d_TEntity_CollisionNX"
-CollisionNY#(index%)="_sidesign_minib3d_TEntity_CollisionNY"
-CollisionNZ#(index%)="_sidesign_minib3d_TEntity_CollisionNZ"
-CollisionTime#(index%)="_sidesign_minib3d_TEntity_CollisionTime"
-CollisionEntity:TEntity(index%)="_sidesign_minib3d_TEntity_CollisionEntity"
-CollisionSurface:TSurface(index%)="_sidesign_minib3d_TEntity_CollisionSurface"
-CollisionTriangle%(index%)="_sidesign_minib3d_TEntity_CollisionTriangle"
-GetEntityType%()="_sidesign_minib3d_TEntity_GetEntityType"
-MeshCullRadius%(radius#)="_sidesign_minib3d_TEntity_MeshCullRadius"
-EntityScaleX#(glob%=0)="_sidesign_minib3d_TEntity_EntityScaleX"
-EntityScaleY#(glob%=0)="_sidesign_minib3d_TEntity_EntityScaleY"
-EntityScaleZ#(glob%=0)="_sidesign_minib3d_TEntity_EntityScaleZ"
-BoundingSphereNew%(sx# Var,sy# Var,sz# Var,sr# Var)="_sidesign_minib3d_TEntity_BoundingSphereNew"
+CountAllChildren%(ent:TEntity,no_children%=0)="_sidesign_minib3d_TEntity_CountAllChildren"
-GetChildFromAll:TEntity(child_no%,no_children% Var,ent:TEntity="bbNullObject")="_sidesign_minib3d_TEntity_GetChildFromAll"
-UpdateMat%(load_identity%=0)="_sidesign_minib3d_TEntity_UpdateMat"
-AddParent%(parent_ent:TEntity)="_sidesign_minib3d_TEntity_AddParent"
+UpdateChildren%(ent_p:TEntity)="_sidesign_minib3d_TEntity_UpdateChildren"
-EntityDistanceSquared0#(ent2:TEntity)="_sidesign_minib3d_TEntity_EntityDistanceSquared0"
-EntityDistanceSquared#(ent2:TEntity)="_sidesign_minib3d_TEntity_EntityDistanceSquared"
-EntityListAdd%(list:TList)="_sidesign_minib3d_TEntity_EntityListAdd"
}A="sidesign_minib3d_TEntity"
TCamera^TEntity{
cam_list:TList&=mem:p("_sidesign_minib3d_TCamera_cam_list")
projected_x#&=mem:f("_sidesign_minib3d_TCamera_projected_x")
projected_y#&=mem:f("_sidesign_minib3d_TCamera_projected_y")
projected_z#&=mem:f("_sidesign_minib3d_TCamera_projected_z")
.vx%&
.vy%&
.vwidth%&
.vheight%&
.cls_r#&
.cls_g#&
.cls_b#&
.cls_color%&
.cls_zbuffer%&
.range_near#&
.range_far#&
.zoom#&
.proj_mode%&
.fog_mode%&
.fog_r#&
.fog_g#&
.fog_b#&
.fog_range_near#&
.fog_range_far#&
.mod_mat!&[]&
.proj_mat!&[]&
.viewport%&[]&
.frustum#&[,]&
-New%()="_sidesign_minib3d_TCamera_New"
-Delete%()="_sidesign_minib3d_TCamera_Delete"
-CopyEntity:TCamera(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TCamera_CopyEntity"
-FreeEntity%()="_sidesign_minib3d_TCamera_FreeEntity"
+CreateCamera:TCamera(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TCamera_CreateCamera"
-CameraViewport%(x%,y%,w%,h%)="_sidesign_minib3d_TCamera_CameraViewport"
-CameraClsColor%(r#,g#,b#)="_sidesign_minib3d_TCamera_CameraClsColor"
-CameraClsMode%(color%,zbuffer%)="_sidesign_minib3d_TCamera_CameraClsMode"
-CameraRange%(near#,far#)="_sidesign_minib3d_TCamera_CameraRange"
-CameraZoom%(zoom_val#)="_sidesign_minib3d_TCamera_CameraZoom"
-CameraProjMode%(mode%=1)="_sidesign_minib3d_TCamera_CameraProjMode"
-CameraPick:TEntity(x#,y#)="_sidesign_minib3d_TCamera_CameraPick"
-CameraFogMode%(mode%)="_sidesign_minib3d_TCamera_CameraFogMode"
-CameraFogColor%(r#,g#,b#)="_sidesign_minib3d_TCamera_CameraFogColor"
-CameraFogRange%(near#,far#)="_sidesign_minib3d_TCamera_CameraFogRange"
-CameraProject%(x#,y#,z#)="_sidesign_minib3d_TCamera_CameraProject"
-ProjectedX#()="_sidesign_minib3d_TCamera_ProjectedX"
-ProjectedY#()="_sidesign_minib3d_TCamera_ProjectedY"
-ProjectedZ#()="_sidesign_minib3d_TCamera_ProjectedZ"
-EntityInView#(ent:TEntity)="_sidesign_minib3d_TCamera_EntityInView"
-ExtractFrustum%()="_sidesign_minib3d_TCamera_ExtractFrustum"
-EntityInFrustum#(ent:TEntity)="_sidesign_minib3d_TCamera_EntityInFrustum"
-Update%()="_sidesign_minib3d_TCamera_Update"
-accPerspective%(fovy#,aspect#,zNear#,zFar#,pixdx#,pixdy#,eyedx#,eyedy#,focus#)="_sidesign_minib3d_TCamera_accPerspective"
-accFrustum%(left_#,right_#,bottom#,top#,zNear#,zFar#,pixdx#,pixdy#,eyedx#,eyedy#,focus#)="_sidesign_minib3d_TCamera_accFrustum"
}="sidesign_minib3d_TCamera"
TLight^TEntity{
light_no%&=mem("_sidesign_minib3d_TLight_light_no")
no_lights%&=mem("_sidesign_minib3d_TLight_no_lights")
max_lights%&=mem("_sidesign_minib3d_TLight_max_lights")
gl_light%&[]&=mem:p("_sidesign_minib3d_TLight_gl_light")
light_list:TList&=mem:p("_sidesign_minib3d_TLight_light_list")
.light_type%&
.range#&
.red#&
.green#&
.blue#&
.inner_ang#&
.outer_ang#&
-New%()="_sidesign_minib3d_TLight_New"
-Delete%()="_sidesign_minib3d_TLight_Delete"
-CopyEntity:TLight(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TLight_CopyEntity"
-FreeEntity%()="_sidesign_minib3d_TLight_FreeEntity"
+CreateLight:TLight(l_type%=1,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TLight_CreateLight"
-LightRange%(light_range#)="_sidesign_minib3d_TLight_LightRange"
-LightColor%(r#,g#,b#)="_sidesign_minib3d_TLight_LightColor"
-LightConeAngles%(inner#,outer#)="_sidesign_minib3d_TLight_LightConeAngles"
-Update%()="_sidesign_minib3d_TLight_Update"
}="sidesign_minib3d_TLight"
TPivot^TEntity{
-New%()="_sidesign_minib3d_TPivot_New"
-Delete%()="_sidesign_minib3d_TPivot_Delete"
-CopyEntity:TPivot(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TPivot_CopyEntity"
-FreeEntity%()="_sidesign_minib3d_TPivot_FreeEntity"
+CreatePivot:TPivot(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TPivot_CreatePivot"
-Update%()="_sidesign_minib3d_TPivot_Update"
}="sidesign_minib3d_TPivot"
TMesh^TEntity{
.min_x#&
.min_y#&
.min_z#&
.max_x#&
.max_y#&
.max_z#&
.no_surfs%&
.surf_list:TList&
.anim_surf_list:TList&
.no_bones%&
.bones:TBone&[]&
.mat_sp:TMatrix&
.col_tree:TColTree&
.reset_bounds%&
-New%()="_sidesign_minib3d_TMesh_New"
-Delete%()="_sidesign_minib3d_TMesh_Delete"
-CopyEntity:TMesh(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CopyEntity"
-FreeEntity%()="_sidesign_minib3d_TMesh_FreeEntity"
+CreateMesh:TMesh(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CreateMesh"
+LoadMesh:TMesh(file$,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_LoadMesh"
+LoadAnimMesh:TMesh(file$,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_LoadAnimMesh"
+CreateCube:TMesh(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CreateCube"
+CreateSphere:TMesh(segments%=8,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CreateSphere"
+CreateCylinder:TMesh(verticalsegments%=8,solid%=1,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CreateCylinder"
+CreateCone:TMesh(segments%=8,solid%=1,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CreateCone"
-CopyMesh:TMesh(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TMesh_CopyMesh"
-AddMesh%(mesh2:TMesh)="_sidesign_minib3d_TMesh_AddMesh"
-FlipMesh%()="_sidesign_minib3d_TMesh_FlipMesh"
-PaintMesh%(bru:TBrush)="_sidesign_minib3d_TMesh_PaintMesh"
-FitMesh%(x#,y#,z#,width#,height#,depth#,uniform%=0)="_sidesign_minib3d_TMesh_FitMesh"
-ScaleMesh%(sx#,sy#,sz#)="_sidesign_minib3d_TMesh_ScaleMesh"
-RotateMesh%(pitch#,yaw#,roll#)="_sidesign_minib3d_TMesh_RotateMesh"
-PositionMesh%(px#,py#,pz#)="_sidesign_minib3d_TMesh_PositionMesh"
-UpdateNormals%()="_sidesign_minib3d_TMesh_UpdateNormals"
-CreateSurface:TSurface(bru:TBrush="bbNullObject")="_sidesign_minib3d_TMesh_CreateSurface"
-MeshWidth#()="_sidesign_minib3d_TMesh_MeshWidth"
-MeshHeight#()="_sidesign_minib3d_TMesh_MeshHeight"
-MeshDepth#()="_sidesign_minib3d_TMesh_MeshDepth"
-CountSurfaces%()="_sidesign_minib3d_TMesh_CountSurfaces"
-GetSurface:TSurface(surf_no_get%)="_sidesign_minib3d_TMesh_GetSurface"
-FindSurface:TSurface(brush:TBrush)="_sidesign_minib3d_TMesh_FindSurface"
-CountVertices%()="_sidesign_minib3d_TMesh_CountVertices"
-CountTriangles%()="_sidesign_minib3d_TMesh_CountTriangles"
+CopyBonesList%(ent:TEntity,bones:TBone&[] Var,no_bones% Var)="_sidesign_minib3d_TMesh_CopyBonesList"
-CollapseAnimMesh:TMesh(mesh:TMesh="bbNullObject")="_sidesign_minib3d_TMesh_CollapseAnimMesh"
+CollapseChildren:TMesh(ent0:TEntity,mesh:TMesh="bbNullObject")="_sidesign_minib3d_TMesh_CollapseChildren"
-TransformMesh%(mat:TMatrix)="_sidesign_minib3d_TMesh_TransformMesh"
-GetBounds%()="_sidesign_minib3d_TMesh_GetBounds"
-Alpha%()="_sidesign_minib3d_TMesh_Alpha"
-Update%()="_sidesign_minib3d_TMesh_Update"
}="sidesign_minib3d_TMesh"
TSprite^TMesh{
.angle#&
.scale_x#&
.scale_y#&
.handle_x#&
.handle_y#&
.view_mode%&
-New%()="_sidesign_minib3d_TSprite_New"
-Delete%()="_sidesign_minib3d_TSprite_Delete"
-CopyEntity:TSprite(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TSprite_CopyEntity"
+CreateSprite:TSprite(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TSprite_CreateSprite"
+LoadSprite:TSprite(tex_file$,tex_flag%=1,parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TSprite_LoadSprite"
-RotateSprite%(ang#)="_sidesign_minib3d_TSprite_RotateSprite"
-ScaleSprite%(s_x#,s_y#)="_sidesign_minib3d_TSprite_ScaleSprite"
-HandleSprite%(h_x#,h_y#)="_sidesign_minib3d_TSprite_HandleSprite"
-SpriteViewMode%(mode%)="_sidesign_minib3d_TSprite_SpriteViewMode"
}="sidesign_minib3d_TSprite"
TBone^TEntity{
.n_px#&
.n_py#&
.n_pz#&
.n_sx#&
.n_sy#&
.n_sz#&
.n_rx#&
.n_ry#&
.n_rz#&
.n_qw#&
.n_qx#&
.n_qy#&
.n_qz#&
.keys:TAnimationKeys&
.mat2:TMatrix&
.inv_mat:TMatrix&
.tform_mat:TMatrix&
.kx#&
.ky#&
.kz#&
.kqw#&
.kqx#&
.kqy#&
.kqz#&
-New%()="_sidesign_minib3d_TBone_New"
-Delete%()="_sidesign_minib3d_TBone_Delete"
-CopyEntity:TBone(parent_ent:TEntity="bbNullObject")="_sidesign_minib3d_TBone_CopyEntity"
-FreeEntity%()="_sidesign_minib3d_TBone_FreeEntity"
+UpdateBoneChildren%(ent_p:TEntity)="_sidesign_minib3d_TBone_UpdateBoneChildren"
-Update%()="_sidesign_minib3d_TBone_Update"
}="sidesign_minib3d_TBone"
TSurface^Object{
.no_verts%&
.no_tris%&
.tris@@&[]&
.vert_coords#&[]&
.vert_tex_coords0#&[]&
.vert_tex_coords1#&[]&
.vert_norm#&[]&
.vert_col#&[]&
.vert_bone1_no%&[]&
.vert_bone2_no%&[]&
.vert_bone3_no%&[]&
.vert_bone4_no%&[]&
.vert_weight1#&[]&
.vert_weight2#&[]&
.vert_weight3#&[]&
.vert_weight4#&[]&
.brush:TBrush&
.vbo_id%&[]&
.vert_array_size%&
.tri_array_size%&
.vmin%&
.vmax%&
.reset_vbo%&
.alpha_enable%&
-New%()="_sidesign_minib3d_TSurface_New"
-Delete%()="_sidesign_minib3d_TSurface_Delete"
-Compare%(other:Object)="_sidesign_minib3d_TSurface_Compare"
-Copy:TSurface()="_sidesign_minib3d_TSurface_Copy"
-PaintSurface%(bru:TBrush)="_sidesign_minib3d_TSurface_PaintSurface"
-ClearSurface%(clear_verts%=1,clear_tris%=1)="_sidesign_minib3d_TSurface_ClearSurface"
-AddVertex%(x#,y#,z#,u#=0#,v#=0#,w#=0#)="_sidesign_minib3d_TSurface_AddVertex"
-AddTriangle%(v0%,v1%,v2%)="_sidesign_minib3d_TSurface_AddTriangle"
-CountVertices%()="_sidesign_minib3d_TSurface_CountVertices"
-CountTriangles%()="_sidesign_minib3d_TSurface_CountTriangles"
-VertexCoords%(vid%,x#,y#,z#)="_sidesign_minib3d_TSurface_VertexCoords"
-VertexColor%(vid%,r#,g#,b#,a#=1#)="_sidesign_minib3d_TSurface_VertexColor"
-VertexNormal%(vid%,nx#,ny#,nz#)="_sidesign_minib3d_TSurface_VertexNormal"
-VertexTexCoords%(vid%,u#,v#,w#=0#,coord_set%=0)="_sidesign_minib3d_TSurface_VertexTexCoords"
-VertexX#(vid%)="_sidesign_minib3d_TSurface_VertexX"
-VertexY#(vid%)="_sidesign_minib3d_TSurface_VertexY"
-VertexZ#(vid%)="_sidesign_minib3d_TSurface_VertexZ"
-VertexRed#(vid%)="_sidesign_minib3d_TSurface_VertexRed"
-VertexGreen#(vid%)="_sidesign_minib3d_TSurface_VertexGreen"
-VertexBlue#(vid%)="_sidesign_minib3d_TSurface_VertexBlue"
-VertexAlpha#(vid%)="_sidesign_minib3d_TSurface_VertexAlpha"
-VertexNX#(vid%)="_sidesign_minib3d_TSurface_VertexNX"
-VertexNY#(vid%)="_sidesign_minib3d_TSurface_VertexNY"
-VertexNZ#(vid%)="_sidesign_minib3d_TSurface_VertexNZ"
-VertexU#(vid%,coord_set%=0)="_sidesign_minib3d_TSurface_VertexU"
-VertexV#(vid%,coord_set%=0)="_sidesign_minib3d_TSurface_VertexV"
-VertexW#(vid%,coord_set%=0)="_sidesign_minib3d_TSurface_VertexW"
-TriangleVertex%(tri_no%,corner%)="_sidesign_minib3d_TSurface_TriangleVertex"
-UpdateNormals%()="_sidesign_minib3d_TSurface_UpdateNormals"
-TriangleNX#(tri_no%)="_sidesign_minib3d_TSurface_TriangleNX"
-TriangleNY#(tri_no%)="_sidesign_minib3d_TSurface_TriangleNY"
-TriangleNZ#(tri_no%)="_sidesign_minib3d_TSurface_TriangleNZ"
-UpdateVBO%()="_sidesign_minib3d_TSurface_UpdateVBO"
-FreeVBO%()="_sidesign_minib3d_TSurface_FreeVBO"
+RemoveTri%(surf:TSurface,tri%)="_sidesign_minib3d_TSurface_RemoveTri"
+RemoveVerts%(surf:TSurface)="_sidesign_minib3d_TSurface_RemoveVerts"
}="sidesign_minib3d_TSurface"
TTexture^Object{
tex_list:TList&=mem:p("_sidesign_minib3d_TTexture_tex_list")
.file$&
.flags%&
.blend%&
.coords%&
.u_scale#&
.v_scale#&
.u_pos#&
.v_pos#&
.angle#&
.file_abs$&
.width%&
.height%&
.pixmap:TPixmap&
.gltex%&[]&
.cube_pixmap:TPixmap&[]&
.no_frames%&
.no_mipmaps%&
.cube_face%&
.cube_mode%&
-New%()="_sidesign_minib3d_TTexture_New"
-Delete%()="_sidesign_minib3d_TTexture_Delete"
-FreeTexture%()="_sidesign_minib3d_TTexture_FreeTexture"
+CreateTexture:TTexture(width%,height%,flags%=1,frames%=1,tex:TTexture="bbNullObject")="_sidesign_minib3d_TTexture_CreateTexture"
+LoadTexture:TTexture(file$,flags%=1,tex:TTexture="bbNullObject")="_sidesign_minib3d_TTexture_LoadTexture"
+LoadAnimTexture:TTexture(file$,flags%,frame_width%,frame_height%,first_frame%,frame_count%,tex:TTexture="bbNullObject")="_sidesign_minib3d_TTexture_LoadAnimTexture"
+CreateCubeMapTexture:TTexture(width%,height%,flags%,tex:TTexture="bbNullObject")="_sidesign_minib3d_TTexture_CreateCubeMapTexture"
+LoadCubeMapTexture:TTexture(file$,flags%=1,tex:TTexture="bbNullObject")="_sidesign_minib3d_TTexture_LoadCubeMapTexture"
-TextureBlend%(blend_no%)="_sidesign_minib3d_TTexture_TextureBlend"
-TextureCoords%(coords_no%)="_sidesign_minib3d_TTexture_TextureCoords"
-ScaleTexture%(u_s#,v_s#)="_sidesign_minib3d_TTexture_ScaleTexture"
-PositionTexture%(u_p#,v_p#)="_sidesign_minib3d_TTexture_PositionTexture"
-RotateTexture%(ang#)="_sidesign_minib3d_TTexture_RotateTexture"
-TextureWidth%()="_sidesign_minib3d_TTexture_TextureWidth"
-TextureHeight%()="_sidesign_minib3d_TTexture_TextureHeight"
-TextureName$()="_sidesign_minib3d_TTexture_TextureName"
+GetBrushTexture:TTexture(brush:TBrush,index%=0)="_sidesign_minib3d_TTexture_GetBrushTexture"
+ClearTextureFilters%()="_sidesign_minib3d_TTexture_ClearTextureFilters"
+TextureFilter%(match_text$,flags%)="_sidesign_minib3d_TTexture_TextureFilter"
-SetCubeFace%(face%)="_sidesign_minib3d_TTexture_SetCubeFace"
-SetCubeMode%(mode%)="_sidesign_minib3d_TTexture_SetCubeMode"
-BackBufferToTex%(mipmap_no%=0,frame%=0)="_sidesign_minib3d_TTexture_BackBufferToTex"
-CountMipmaps%()="_sidesign_minib3d_TTexture_CountMipmaps"
-MipmapWidth%(mipmap_no%)="_sidesign_minib3d_TTexture_MipmapWidth"
-MipmapHeight%(mipmap_no%)="_sidesign_minib3d_TTexture_MipmapHeight"
+FileFind%(file$ Var)="_sidesign_minib3d_TTexture_FileFind"
+FileAbs$(file$)="_sidesign_minib3d_TTexture_FileAbs"
-TexInList:TTexture()="_sidesign_minib3d_TTexture_TexInList"
-FilterFlags%()="_sidesign_minib3d_TTexture_FilterFlags"
+AdjustPixmap:TPixmap(pixmap:TPixmap)="_sidesign_minib3d_TTexture_AdjustPixmap"
+Pow2Size%(n%)="_sidesign_minib3d_TTexture_Pow2Size"
+ApplyAlpha:TPixmap(pixmap:TPixmap)="_sidesign_minib3d_TTexture_ApplyAlpha"
}="sidesign_minib3d_TTexture"
TTextureFilter^Object{
filter_list:TList&=mem:p("_sidesign_minib3d_TTextureFilter_filter_list")
.text$&
.flags%&
-New%()="_sidesign_minib3d_TTextureFilter_New"
-Delete%()="_sidesign_minib3d_TTextureFilter_Delete"
}="sidesign_minib3d_TTextureFilter"
TBrush^Object{
.no_texs%&
.name$&
.red#&
.green#&
.blue#&
.alpha#&
.shine#&
.blend%&
.fx%&
.tex_frame%&
.tex:TTexture&[]&
-New%()="_sidesign_minib3d_TBrush_New"
-Delete%()="_sidesign_minib3d_TBrush_Delete"
-Copy:TBrush()="_sidesign_minib3d_TBrush_Copy"
-FreeBrush%()="_sidesign_minib3d_TBrush_FreeBrush"
+CreateBrush:TBrush(r#=255#,g#=255#,b#=255#)="_sidesign_minib3d_TBrush_CreateBrush"
+LoadBrush:TBrush(file$,flags%=1,u_scale#=1#,v_scale#=1#)="_sidesign_minib3d_TBrush_LoadBrush"
-BrushColor%(r#,g#,b#)="_sidesign_minib3d_TBrush_BrushColor"
-BrushAlpha%(a#)="_sidesign_minib3d_TBrush_BrushAlpha"
-BrushShininess%(s#)="_sidesign_minib3d_TBrush_BrushShininess"
-BrushTexture%(texture:TTexture,frame%=0,index%=0)="_sidesign_minib3d_TBrush_BrushTexture"
-BrushBlend%(blend_no%)="_sidesign_minib3d_TBrush_BrushBlend"
-BrushFX%(fx_no%)="_sidesign_minib3d_TBrush_BrushFX"
+GetEntityBrush:TBrush(ent:TEntity)="_sidesign_minib3d_TBrush_GetEntityBrush"
+GetSurfaceBrush:TBrush(surf:TSurface)="_sidesign_minib3d_TBrush_GetSurfaceBrush"
+CompareBrushes%(brush1:TBrush,brush2:TBrush)="_sidesign_minib3d_TBrush_CompareBrushes"
}="sidesign_minib3d_TBrush"
TAnimation^Object{
-New%()="_sidesign_minib3d_TAnimation_New"
-Delete%()="_sidesign_minib3d_TAnimation_Delete"
+AnimateMesh%(ent1:TEntity,framef#,start_frame%,end_frame%)="_sidesign_minib3d_TAnimation_AnimateMesh"
+AnimateMesh2%(ent1:TEntity,framef#,start_frame%,end_frame%)="_sidesign_minib3d_TAnimation_AnimateMesh2"
+VertexDeform%(ent:TMesh)="_sidesign_minib3d_TAnimation_VertexDeform"
+NormaliseWeights%(mesh:TMesh)="_sidesign_minib3d_TAnimation_NormaliseWeights"
}="sidesign_minib3d_TAnimation"
TAnimationKeys^Object{
.frames%&
.flags%&[]&
.px#&[]&
.py#&[]&
.pz#&[]&
.sx#&[]&
.sy#&[]&
.sz#&[]&
.qw#&[]&
.qx#&[]&
.qy#&[]&
.qz#&[]&
-New%()="_sidesign_minib3d_TAnimationKeys_New"
-Delete%()="_sidesign_minib3d_TAnimationKeys_Delete"
-Copy:TAnimationKeys()="_sidesign_minib3d_TAnimationKeys_Copy"
}="sidesign_minib3d_TAnimationKeys"
TModel^Object{
-New%()="_sidesign_minib3d_TModel_New"
-Delete%()="_sidesign_minib3d_TModel_Delete"
+LoadAnimB3D:TMesh(f_name$,parent_ent_ext:TEntity="bbNullObject")="_sidesign_minib3d_TModel_LoadAnimB3D"
+TrimVerts%(surf:TSurface Var)="_sidesign_minib3d_TModel_TrimVerts"
+b3dReadString$(file:TStream Var)="_sidesign_minib3d_TModel_b3dReadString"
+ReadTag$(file:TStream)="_sidesign_minib3d_TModel_ReadTag"
+NewTag%(tag$)="_sidesign_minib3d_TModel_NewTag"
}="sidesign_minib3d_TModel"
TColTree^Object{
.c_col_tree@*&
.reset_col_tree%&
-New%()="_sidesign_minib3d_TColTree_New"
-Delete%()="_sidesign_minib3d_TColTree_Delete"
-TreeCheck%(mesh:TMesh)="_sidesign_minib3d_TColTree_TreeCheck"
}="sidesign_minib3d_TColTree"
TPick^Object{
EPSILON#=0.0001#
ent_list:TList&=mem:p("_sidesign_minib3d_TPick_ent_list")
picked_x#&=mem:f("_sidesign_minib3d_TPick_picked_x")
picked_y#&=mem:f("_sidesign_minib3d_TPick_picked_y")
picked_z#&=mem:f("_sidesign_minib3d_TPick_picked_z")
picked_nx#&=mem:f("_sidesign_minib3d_TPick_picked_nx")
picked_ny#&=mem:f("_sidesign_minib3d_TPick_picked_ny")
picked_nz#&=mem:f("_sidesign_minib3d_TPick_picked_nz")
picked_time#&=mem:f("_sidesign_minib3d_TPick_picked_time")
picked_ent:TEntity&=mem:p("_sidesign_minib3d_TPick_picked_ent")
picked_surface:TSurface&=mem:p("_sidesign_minib3d_TPick_picked_surface")
picked_triangle%&=mem("_sidesign_minib3d_TPick_picked_triangle")
-New%()="_sidesign_minib3d_TPick_New"
-Delete%()="_sidesign_minib3d_TPick_Delete"
+CameraPick:TEntity(cam:TCamera,vx#,vy#)="_sidesign_minib3d_TPick_CameraPick"
+EntityPick:TEntity(ent:TEntity,range#)="_sidesign_minib3d_TPick_EntityPick"
+LinePick:TEntity(x#,y#,z#,dx#,dy#,dz#,radius#=0#)="_sidesign_minib3d_TPick_LinePick"
+EntityVisible%(src_ent:TEntity,dest_ent:TEntity)="_sidesign_minib3d_TPick_EntityVisible"
+PickedX#()="_sidesign_minib3d_TPick_PickedX"
+PickedY#()="_sidesign_minib3d_TPick_PickedY"
+PickedZ#()="_sidesign_minib3d_TPick_PickedZ"
+PickedNX#()="_sidesign_minib3d_TPick_PickedNX"
+PickedNY#()="_sidesign_minib3d_TPick_PickedNY"
+PickedNZ#()="_sidesign_minib3d_TPick_PickedNZ"
+PickedTime#()="_sidesign_minib3d_TPick_PickedTime"
+PickedEntity:TEntity()="_sidesign_minib3d_TPick_PickedEntity"
+PickedSurface:TSurface()="_sidesign_minib3d_TPick_PickedSurface"
+PickedTriangle%()="_sidesign_minib3d_TPick_PickedTriangle"
+Pick:TEntity(ax#,ay#,az#,bx#,by#,bz#,radius#=0#)="_sidesign_minib3d_TPick_Pick"
}="sidesign_minib3d_TPick"
TCollisionPair^Object{
list:TList&=mem:p("_sidesign_minib3d_TCollisionPair_list")
ent_lists:TList&[]&=mem:p("_sidesign_minib3d_TCollisionPair_ent_lists")
.src_type%&
.des_type%&
.col_method%&
.response%&
-New%()="_sidesign_minib3d_TCollisionPair_New"
-Delete%()="_sidesign_minib3d_TCollisionPair_Delete"
}="sidesign_minib3d_TCollisionPair"
TCollisionImpact^Object{
.x#&
.y#&
.z#&
.nx#&
.ny#&
.nz#&
.time#&
.ent:TEntity&
.surf:TSurface&
.tri%&
-New%()="_sidesign_minib3d_TCollisionImpact_New"
-Delete%()="_sidesign_minib3d_TCollisionImpact_Delete"
}="sidesign_minib3d_TCollisionImpact"
MAX_TYPES%=100
COLLISION_METHOD_SPHERE%=1
COLLISION_METHOD_POLYGON%=2
COLLISION_METHOD_BOX%=3
COLLISION_RESPONSE_NONE%=0
COLLISION_RESPONSE_STOP%=1
COLLISION_RESPONSE_SLIDE%=2
COLLISION_RESPONSE_SLIDEXZ%=3
UpdateCollisions%()="sidesign_minib3d_UpdateCollisions"
QuickCheck%(ent:TEntity,ent2:TEntity)="sidesign_minib3d_QuickCheck"
TVector^Object{
EPSILON#=0.0001#
.x#&
.y#&
.z#&
-New%()="_sidesign_minib3d_TVector_New"
-Delete%()="_sidesign_minib3d_TVector_Delete"
+Create:TVector(x#,y#,z#)="_sidesign_minib3d_TVector_Create"
-Copy:TVector()="_sidesign_minib3d_TVector_Copy"
-Add:TVector(vec:TVector)="_sidesign_minib3d_TVector_Add"
-Subtract:TVector(vec:TVector)="_sidesign_minib3d_TVector_Subtract"
-Multiply:TVector(val#)="_sidesign_minib3d_TVector_Multiply"
-Divide:TVector(val#)="_sidesign_minib3d_TVector_Divide"
-Dot#(vec:TVector)="_sidesign_minib3d_TVector_Dot"
-Cross:TVector(vec:TVector)="_sidesign_minib3d_TVector_Cross"
-Normalize%()="_sidesign_minib3d_TVector_Normalize"
-Length#()="_sidesign_minib3d_TVector_Length"
-SquaredLength#()="_sidesign_minib3d_TVector_SquaredLength"
-SetLength#(val#)="_sidesign_minib3d_TVector_SetLength"
-Compare%(with:Object)="_sidesign_minib3d_TVector_Compare"
+VectorYaw#(vx#,vy#,vz#)="_sidesign_minib3d_TVector_VectorYaw"
+VectorPitch#(vx#,vy#,vz#)="_sidesign_minib3d_TVector_VectorPitch"
}="sidesign_minib3d_TVector"
TMatrix^Object{
.grid#&[,]&
-New%()="_sidesign_minib3d_TMatrix_New"
-Delete%()="_sidesign_minib3d_TMatrix_Delete"
-LoadIdentity%()="_sidesign_minib3d_TMatrix_LoadIdentity"
-Copy:TMatrix()="_sidesign_minib3d_TMatrix_Copy"
-Overwrite%(mat:TMatrix)="_sidesign_minib3d_TMatrix_Overwrite"
-Inverse:TMatrix()="_sidesign_minib3d_TMatrix_Inverse"
-Multiply%(mat:TMatrix)="_sidesign_minib3d_TMatrix_Multiply"
-Translate%(x#,y#,z#)="_sidesign_minib3d_TMatrix_Translate"
-Scale%(x#,y#,z#)="_sidesign_minib3d_TMatrix_Scale"
-Rotate%(rx#,ry#,rz#)="_sidesign_minib3d_TMatrix_Rotate"
-RotatePitch%(ang#)="_sidesign_minib3d_TMatrix_RotatePitch"
-RotateYaw%(ang#)="_sidesign_minib3d_TMatrix_RotateYaw"
-RotateRoll%(ang#)="_sidesign_minib3d_TMatrix_RotateRoll"
}="sidesign_minib3d_TMatrix"
TQuaternion^Object{
.w#&
.x#&
.y#&
.z#&
-New%()="_sidesign_minib3d_TQuaternion_New"
-Delete%()="_sidesign_minib3d_TQuaternion_Delete"
+QuatToMat%(w#,x#,y#,z#,mat:TMatrix Var)="_sidesign_minib3d_TQuaternion_QuatToMat"
+QuatToEuler%(w#,x#,y#,z#,pitch# Var,yaw# Var,roll# Var)="_sidesign_minib3d_TQuaternion_QuatToEuler"
+Slerp%(Ax#,Ay#,Az#,Aw#,Bx#,By#,Bz#,Bw#,Cx# Var,Cy# Var,Cz# Var,Cw# Var,t#)="_sidesign_minib3d_TQuaternion_Slerp"
}="sidesign_minib3d_TQuaternion"
BoxFromPoints%(px1#,py1#,pz1#,px2#,py2#,pz2#,bx1# Var,by1# Var,bz1# Var,bx2# Var,by2# Var,bz2# Var)="sidesign_minib3d_BoxFromPoints"
BoxFromTri%(tx1#,ty1#,tz1#,tx2#,ty2#,tz2#,tx3#,ty3#,tz3#,bx1# Var,by1# Var,bz1# Var,bx2# Var,by2# Var,bz2# Var)="sidesign_minib3d_BoxFromTri"
BoxBoxIntersection%(ax1#,ay1#,az1#,ax2#,ay2#,az2#,bx1#,by1#,bz1#,bx2#,by2#,bz2#)="sidesign_minib3d_BoxBoxIntersection"
BoxSphereIntersection%(x1#,y1#,z1#,x2#,y2#,z2#,sx#,sy#,sz#,sr#)="sidesign_minib3d_BoxSphereIntersection"
THardwareInfo^Object{
ScreenWidth%&=mem("_sidesign_minib3d_THardwareInfo_ScreenWidth")
ScreenHeight%&=mem("_sidesign_minib3d_THardwareInfo_ScreenHeight")
ScreenDepth%&=mem("_sidesign_minib3d_THardwareInfo_ScreenDepth")
ScreenHertz%&=mem("_sidesign_minib3d_THardwareInfo_ScreenHertz")
Vendor$&=mem:p("_sidesign_minib3d_THardwareInfo_Vendor")
Renderer$&=mem:p("_sidesign_minib3d_THardwareInfo_Renderer")
OGLVersion$&=mem:p("_sidesign_minib3d_THardwareInfo_OGLVersion")
Extensions$&=mem:p("_sidesign_minib3d_THardwareInfo_Extensions")
VBOSupport%&=mem("_sidesign_minib3d_THardwareInfo_VBOSupport")
GLTCSupport%&=mem("_sidesign_minib3d_THardwareInfo_GLTCSupport")
S3TCSupport%&=mem("_sidesign_minib3d_THardwareInfo_S3TCSupport")
AnIsoSupport%&=mem("_sidesign_minib3d_THardwareInfo_AnIsoSupport")
MultiTexSupport%&=mem("_sidesign_minib3d_THardwareInfo_MultiTexSupport")
TexBlendSupport%&=mem("_sidesign_minib3d_THardwareInfo_TexBlendSupport")
CubemapSupport%&=mem("_sidesign_minib3d_THardwareInfo_CubemapSupport")
DepthmapSupport%&=mem("_sidesign_minib3d_THardwareInfo_DepthmapSupport")
VPSupport%&=mem("_sidesign_minib3d_THardwareInfo_VPSupport")
FPSupport%&=mem("_sidesign_minib3d_THardwareInfo_FPSupport")
ShaderSupport%&=mem("_sidesign_minib3d_THardwareInfo_ShaderSupport")
VSSupport%&=mem("_sidesign_minib3d_THardwareInfo_VSSupport")
FSSupport%&=mem("_sidesign_minib3d_THardwareInfo_FSSupport")
SLSupport%&=mem("_sidesign_minib3d_THardwareInfo_SLSupport")
MaxTextures%&=mem("_sidesign_minib3d_THardwareInfo_MaxTextures")
MaxTexSize%&=mem("_sidesign_minib3d_THardwareInfo_MaxTexSize")
MaxLights%&=mem("_sidesign_minib3d_THardwareInfo_MaxLights")
-New%()="_sidesign_minib3d_THardwareInfo_New"
-Delete%()="_sidesign_minib3d_THardwareInfo_Delete"
+GetInfo%()="_sidesign_minib3d_THardwareInfo_GetInfo"
+DisplayInfo%(LogFile%=0)="_sidesign_minib3d_THardwareInfo_DisplayInfo"
}="sidesign_minib3d_THardwareInfo"
TBlitz2D^Object{
-New%()="_sidesign_minib3d_TBlitz2D_New"
-Delete%()="_sidesign_minib3d_TBlitz2D_Delete"
+Text%(x%,y%,text$)="_sidesign_minib3d_TBlitz2D_Text"
+BeginMax2D%()="_sidesign_minib3d_TBlitz2D_BeginMax2D"
+EndMax2D%()="_sidesign_minib3d_TBlitz2D_EndMax2D"
}="sidesign_minib3d_TBlitz2D"
TUtility^Object{
-New%()="_sidesign_minib3d_TUtility_New"
-Delete%()="_sidesign_minib3d_TUtility_Delete"
+UpdateValue#(current#,destination#,rate#)="_sidesign_minib3d_TUtility_UpdateValue"
}="sidesign_minib3d_TUtility"
TDebug^Object{
cno%&=mem("_sidesign_minib3d_TDebug_cno")
surf_no%&=mem("_sidesign_minib3d_TDebug_surf_no")
info%&=mem("_sidesign_minib3d_TDebug_info")
show_ents%&=mem("_sidesign_minib3d_TDebug_show_ents")
bounding_sphere:TMesh&=mem:p("_sidesign_minib3d_TDebug_bounding_sphere")
debug_mesh:TMesh&=mem:p("_sidesign_minib3d_TDebug_debug_mesh")
debug_surf:TSurface&=mem:p("_sidesign_minib3d_TDebug_debug_surf")
marker:TMesh&=mem:p("_sidesign_minib3d_TDebug_marker")
-New%()="_sidesign_minib3d_TDebug_New"
-Delete%()="_sidesign_minib3d_TDebug_Delete"
+DebugWorld%()="_sidesign_minib3d_TDebug_DebugWorld"
+DebugEntity:TEntity(ent:TEntity,cam:TCamera="bbNullObject")="_sidesign_minib3d_TDebug_DebugEntity"
+UpdateBoundingSphere%(ent:TEntity)="_sidesign_minib3d_TDebug_UpdateBoundingSphere"
+UpdateSurface%(ent:TEntity,surf:TSurface)="_sidesign_minib3d_TDebug_UpdateSurface"
+UpdateMarker%(ent:TEntity,cam:TCamera)="_sidesign_minib3d_TDebug_UpdateMarker"
+EntityInfo1%(ent:TEntity)="_sidesign_minib3d_TDebug_EntityInfo1"
+EntityInfo2%(ent:TEntity,surf:TSurface)="_sidesign_minib3d_TDebug_EntityInfo2"
+EntityInfo3%(ent:TEntity,surf:TSurface)="_sidesign_minib3d_TDebug_EntityInfo3"
+EntityInfo4%(ent:TEntity,cam:TCamera)="_sidesign_minib3d_TDebug_EntityInfo4"
}="sidesign_minib3d_TDebug"
BackBufferToTex%(tex:TTexture,mipmap_no%=0,frame%=0)="sidesign_minib3d_BackBufferToTex"
MeshCullRadius%(ent:TEntity,radius#)="sidesign_minib3d_MeshCullRadius"
AddMesh:TMesh(mesh1:TMesh,mesh2:TMesh)="sidesign_minib3d_AddMesh"
AddTriangle%(surf:TSurface,v0%,v1%,v2%)="sidesign_minib3d_AddTriangle"
AddVertex%(surf:TSurface,x#,y#,z#,u#=0#,v#=0#,w#=0#)="sidesign_minib3d_AddVertex"
AmbientLight%(r#,g#,b#)="sidesign_minib3d_AmbientLight"
AntiAlias%(samples%)="sidesign_minib3d_AntiAlias"
Animate%(ent:TEntity,mode%=1,speed#=1#,seq%=0,trans%=0)="sidesign_minib3d_Animate"
Animating%(ent:TEntity)="sidesign_minib3d_Animating"
AnimLength%(ent:TEntity)="sidesign_minib3d_AnimLength"
AnimSeq%(ent:TEntity)="sidesign_minib3d_AnimSeq"
AnimTime#(ent:TEntity)="sidesign_minib3d_AnimTime"
BrushAlpha%(brush:TBrush,a#)="sidesign_minib3d_BrushAlpha"
BrushBlend%(brush:TBrush,blend%)="sidesign_minib3d_BrushBlend"
BrushColor%(brush:TBrush,r#,g#,b#)="sidesign_minib3d_BrushColor"
BrushFX%(brush:TBrush,fx%)="sidesign_minib3d_BrushFX"
BrushShininess%(brush:TBrush,s#)="sidesign_minib3d_BrushShininess"
BrushTexture%(brush:TBrush,tex:TTexture,frame%=0,index%=0)="sidesign_minib3d_BrushTexture"
CameraClsColor%(cam:TCamera,r#,g#,b#)="sidesign_minib3d_CameraClsColor"
CameraClsMode%(cam:TCamera,cls_depth%,cls_zbuffer%)="sidesign_minib3d_CameraClsMode"
CameraFogColor%(cam:TCamera,r#,g#,b#)="sidesign_minib3d_CameraFogColor"
CameraFogMode%(cam:TCamera,mode%)="sidesign_minib3d_CameraFogMode"
CameraFogRange%(cam:TCamera,near#,far#)="sidesign_minib3d_CameraFogRange"
CameraPick:TEntity(cam:TCamera,x#,y#)="sidesign_minib3d_CameraPick"
CameraProject%(cam:TCamera,x#,y#,z#)="sidesign_minib3d_CameraProject"
CameraProjMode%(cam:TCamera,mode%)="sidesign_minib3d_CameraProjMode"
CameraRange%(cam:TCamera,near#,far#)="sidesign_minib3d_CameraRange"
CameraViewport%(cam:TCamera,x%,y%,width%,height%)="sidesign_minib3d_CameraViewport"
CameraZoom%(cam:TCamera,zoom#)="sidesign_minib3d_CameraZoom"
ClearCollisions%()="sidesign_minib3d_ClearCollisions"
ClearSurface%(surf:TSurface,clear_verts%=1,clear_tris%=1)="sidesign_minib3d_ClearSurface"
ClearTextureFilters%()="sidesign_minib3d_ClearTextureFilters"
ClearWorld%(entities%=1,brushes%=1,textures%=1)="sidesign_minib3d_ClearWorld"
CollisionEntity:TEntity(ent:TEntity,index%)="sidesign_minib3d_CollisionEntity"
Collisions%(src_no%,dest_no%,method_no%,response_no%=0)="sidesign_minib3d_Collisions"
CollisionNX#(ent:TEntity,index%)="sidesign_minib3d_CollisionNX"
CollisionNY#(ent:TEntity,index%)="sidesign_minib3d_CollisionNY"
CollisionNZ#(ent:TEntity,index%)="sidesign_minib3d_CollisionNZ"
CollisionSurface:TSurface(ent:TEntity,index%)="sidesign_minib3d_CollisionSurface"
CollisionTime#(ent:TEntity,index%)="sidesign_minib3d_CollisionTime"
CollisionTriangle%(ent:TEntity,index%)="sidesign_minib3d_CollisionTriangle"
CollisionX#(ent:TEntity,index%)="sidesign_minib3d_CollisionX"
CollisionY#(ent:TEntity,index%)="sidesign_minib3d_CollisionY"
CollisionZ#(ent:TEntity,index%)="sidesign_minib3d_CollisionZ"
CountChildren%(ent:TEntity)="sidesign_minib3d_CountChildren"
CountCollisions%(ent:TEntity)="sidesign_minib3d_CountCollisions"
CopyEntity:TEntity(ent:TEntity,parent:TEntity="bbNullObject")="sidesign_minib3d_CopyEntity"
CopyMesh:TMesh(mesh:TMesh,parent:TEntity="bbNullObject")="sidesign_minib3d_CopyMesh"
CountSurfaces%(mesh:TMesh)="sidesign_minib3d_CountSurfaces"
CountTriangles%(surf:TSurface)="sidesign_minib3d_CountTriangles"
CountVertices%(surf:TSurface)="sidesign_minib3d_CountVertices"
CreateBrush:TBrush(r#=255#,g#=255#,b#=255#)="sidesign_minib3d_CreateBrush"
CreateCamera:TCamera(parent:TEntity="bbNullObject")="sidesign_minib3d_CreateCamera"
CreateCone:TMesh(segments%=8,solid%=1,parent:TEntity="bbNullObject")="sidesign_minib3d_CreateCone"
CreateCylinder:TMesh(segments%=8,solid%=1,parent:TEntity="bbNullObject")="sidesign_minib3d_CreateCylinder"
CreateCube:TMesh(parent:TEntity="bbNullObject")="sidesign_minib3d_CreateCube"
CreateMesh:TMesh(parent:TEntity="bbNullObject")="sidesign_minib3d_CreateMesh"
CreateLight:TLight(light_type%=1,parent:TEntity="bbNullObject")="sidesign_minib3d_CreateLight"
CreatePivot:TPivot(parent:TEntity="bbNullObject")="sidesign_minib3d_CreatePivot"
CreateSphere:TMesh(segments%=8,parent:TEntity="bbNullObject")="sidesign_minib3d_CreateSphere"
CreateSprite:TSprite(parent:TEntity="bbNullObject")="sidesign_minib3d_CreateSprite"
CreateSurface:TSurface(mesh:TMesh,brush:TBrush="bbNullObject")="sidesign_minib3d_CreateSurface"
CreateTexture:TTexture(width%,height%,flags%=1,frames%=1)="sidesign_minib3d_CreateTexture"
DeltaPitch#(ent1:TEntity,ent2:TEntity)="sidesign_minib3d_DeltaPitch"
DeltaYaw#(ent1:TEntity,ent2:TEntity)="sidesign_minib3d_DeltaYaw"
EntityAlpha%(ent:TEntity,alpha#)="sidesign_minib3d_EntityAlpha"
EntityAutoFade%(ent:TEntity,near#,far#)="sidesign_minib3d_EntityAutoFade"
EntityBlend%(ent:TEntity,blend%)="sidesign_minib3d_EntityBlend"
EntityBox%(ent:TEntity,x#,y#,z#,w#,h#,d#)="sidesign_minib3d_EntityBox"
EntityClass$(ent:TEntity)="sidesign_minib3d_EntityClass"
EntityCollided:TEntity(ent:TEntity,type_no%)="sidesign_minib3d_EntityCollided"
EntityColor%(ent:TEntity,red#,green#,blue#)="sidesign_minib3d_EntityColor"
EntityDistance#(ent1:TEntity,ent2:TEntity)="sidesign_minib3d_EntityDistance"
EntityFX%(ent:TEntity,fx%)="sidesign_minib3d_EntityFX"
EntityInView%(ent:TEntity,cam:TCamera)="sidesign_minib3d_EntityInView"
EntityName$(ent:TEntity)="sidesign_minib3d_EntityName"
EntityOrder%(ent:TEntity,order%)="sidesign_minib3d_EntityOrder"
EntityParent%(ent:TEntity,parent_ent:TEntity,glob%=1)="sidesign_minib3d_EntityParent"
EntityPick:TEntity(ent:TEntity,range#)="sidesign_minib3d_EntityPick"
EntityPickMode%(ent:TEntity,pick_mode%,obscurer%=1)="sidesign_minib3d_EntityPickMode"
EntityPitch#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityPitch"
EntityRadius%(ent:TEntity,radius_x#,radius_y#=0#)="sidesign_minib3d_EntityRadius"
EntityRoll#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityRoll"
EntityShininess%(ent:TEntity,shine#)="sidesign_minib3d_EntityShininess"
EntityTexture%(ent:TEntity,tex:TTexture,frame%=0,index%=0)="sidesign_minib3d_EntityTexture"
EntityType%(ent:TEntity,type_no%,recursive%=0)="sidesign_minib3d_EntityType"
EntityVisible%(src_ent:TEntity,dest_ent:TEntity)="sidesign_minib3d_EntityVisible"
EntityX#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityX"
EntityY#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityY"
EntityYaw#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityYaw"
EntityZ#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityZ"
ExtractAnimSeq%(ent:TEntity,first_frame%,last_frame%,seq%=0)="sidesign_minib3d_ExtractAnimSeq"
FindChild:TEntity(ent:TEntity,child_name$)="sidesign_minib3d_FindChild"
FindSurface:TSurface(mesh:TMesh,brush:TBrush)="sidesign_minib3d_FindSurface"
FitMesh:TMesh(mesh:TMesh,x#,y#,z#,width#,height#,depth#,uniform%=0)="sidesign_minib3d_FitMesh"
FlipMesh:TMesh(mesh:TMesh)="sidesign_minib3d_FlipMesh"
FreeBrush%(brush:TBrush)="sidesign_minib3d_FreeBrush"
FreeEntity%(ent:TEntity)="sidesign_minib3d_FreeEntity"
FreeTexture:TTexture(tex:TTexture)="sidesign_minib3d_FreeTexture"
GetBrushTexture:TTexture(brush:TBrush,index%=0)="sidesign_minib3d_GetBrushTexture"
GetChild:TEntity(ent:TEntity,child_no%)="sidesign_minib3d_GetChild"
GetEntityBrush:TBrush(ent:TEntity)="sidesign_minib3d_GetEntityBrush"
GetEntityType%(ent:TEntity)="sidesign_minib3d_GetEntityType"
GetMatElement#(ent:TEntity,row%,col%)="sidesign_minib3d_GetMatElement"
GetParent:TEntity(ent:TEntity)="sidesign_minib3d_GetParent"
GetSurface:TSurface(mesh:TMesh,surf_no%)="sidesign_minib3d_GetSurface"
GetSurfaceBrush:TBrush(surf:TSurface)="sidesign_minib3d_GetSurfaceBrush"
Graphics3D%(width%,height%,depth%=0,mode%=0,rate%=60,flags%=-1)="sidesign_minib3d_Graphics3D"
HandleSprite%(sprite:TSprite,h_x#,h_y#)="sidesign_minib3d_HandleSprite"
HideEntity%(ent:TEntity)="sidesign_minib3d_HideEntity"
LightColor%(light:TLight,red#,green#,blue#)="sidesign_minib3d_LightColor"
LightConeAngles%(light:TLight,inner_ang#,outer_ang#)="sidesign_minib3d_LightConeAngles"
LightRange%(light:TLight,range#)="sidesign_minib3d_LightRange"
LinePick:TEntity(x#,y#,z#,dx#,dy#,dz#,radius#=0#)="sidesign_minib3d_LinePick"
LoadAnimMesh:TMesh(file$,parent:TEntity="bbNullObject")="sidesign_minib3d_LoadAnimMesh"
LoadAnimTexture:TTexture(file$,flags%,frame_width%,frame_height%,first_frame%,frame_count%)="sidesign_minib3d_LoadAnimTexture"
LoadBrush:TBrush(file$,flags%=1,u_scale#=1#,v_scale#=1#)="sidesign_minib3d_LoadBrush"
LoadMesh:TMesh(file$,parent:TEntity="bbNullObject")="sidesign_minib3d_LoadMesh"
LoadTexture:TTexture(file$,flags%=1)="sidesign_minib3d_LoadTexture"
LoadSprite:TSprite(tex_file$,tex_flag%=1,parent:TEntity="bbNullObject")="sidesign_minib3d_LoadSprite"
MeshDepth#(mesh:TMesh)="sidesign_minib3d_MeshDepth"
MeshHeight#(mesh:TMesh)="sidesign_minib3d_MeshHeight"
MeshWidth#(mesh:TMesh)="sidesign_minib3d_MeshWidth"
MoveEntity%(ent:TEntity,x#,y#,z#)="sidesign_minib3d_MoveEntity"
NameEntity%(ent:TEntity,name$)="sidesign_minib3d_NameEntity"
PaintEntity%(ent:TEntity,brush:TBrush)="sidesign_minib3d_PaintEntity"
PaintMesh:TMesh(mesh:TMesh,brush:TBrush)="sidesign_minib3d_PaintMesh"
PaintSurface%(surf:TSurface,brush:TBrush)="sidesign_minib3d_PaintSurface"
PickedEntity:TEntity()="sidesign_minib3d_PickedEntity"
PickedNX#()="sidesign_minib3d_PickedNX"
PickedNY#()="sidesign_minib3d_PickedNY"
PickedNZ#()="sidesign_minib3d_PickedNZ"
PickedSurface:TSurface()="sidesign_minib3d_PickedSurface"
PickedTime#()="sidesign_minib3d_PickedTime"
PickedTriangle%()="sidesign_minib3d_PickedTriangle"
PickedX#()="sidesign_minib3d_PickedX"
PickedY#()="sidesign_minib3d_PickedY"
PickedZ#()="sidesign_minib3d_PickedZ"
PointEntity%(ent:TEntity,target_ent:TEntity,roll#=0#)="sidesign_minib3d_PointEntity"
PositionEntity%(ent:TEntity,x#,y#,z#,glob%=0)="sidesign_minib3d_PositionEntity"
PositionMesh:TMesh(mesh:TMesh,px#,py#,pz#)="sidesign_minib3d_PositionMesh"
PositionTexture%(tex:TTexture,u_pos#,v_pos#)="sidesign_minib3d_PositionTexture"
ProjectedX#()="sidesign_minib3d_ProjectedX"
ProjectedY#()="sidesign_minib3d_ProjectedY"
ProjectedZ#()="sidesign_minib3d_ProjectedZ"
RenderWorld%()="sidesign_minib3d_RenderWorld"
ResetEntity%(ent:TEntity)="sidesign_minib3d_ResetEntity"
RotateEntity%(ent:TEntity,x#,y#,z#,glob%=0)="sidesign_minib3d_RotateEntity"
RotateMesh:TMesh(mesh:TMesh,pitch#,yaw#,roll#)="sidesign_minib3d_RotateMesh"
RotateSprite%(sprite:TSprite,ang#)="sidesign_minib3d_RotateSprite"
RotateTexture%(tex:TTexture,ang#)="sidesign_minib3d_RotateTexture"
ScaleEntity%(ent:TEntity,x#,y#,z#,glob%=0)="sidesign_minib3d_ScaleEntity"
ScaleMesh:TMesh(mesh:TMesh,sx#,sy#,sz#)="sidesign_minib3d_ScaleMesh"
ScaleSprite%(sprite:TSprite,s_x#,s_y#)="sidesign_minib3d_ScaleSprite"
ScaleTexture%(tex:TTexture,u_scale#,v_scale#)="sidesign_minib3d_ScaleTexture"
SetAnimTime%(ent:TEntity,time#,seq%=0)="sidesign_minib3d_SetAnimTime"
SetCubeFace%(tex:TTexture,face%)="sidesign_minib3d_SetCubeFace"
SetCubeMode%(tex:TTexture,mode%)="sidesign_minib3d_SetCubeMode"
ShowEntity%(ent:TEntity)="sidesign_minib3d_ShowEntity"
SpriteViewMode%(sprite:TSprite,mode%)="sidesign_minib3d_SpriteViewMode"
TextureBlend%(tex:TTexture,blend%)="sidesign_minib3d_TextureBlend"
TextureCoords%(tex:TTexture,coords%)="sidesign_minib3d_TextureCoords"
TextureHeight%(tex:TTexture)="sidesign_minib3d_TextureHeight"
TextureFilter%(match_text$,flags%)="sidesign_minib3d_TextureFilter"
TextureName$(tex:TTexture)="sidesign_minib3d_TextureName"
TextureWidth%(tex:TTexture)="sidesign_minib3d_TextureWidth"
TFormedX#()="sidesign_minib3d_TFormedX"
TFormedY#()="sidesign_minib3d_TFormedY"
TFormedZ#()="sidesign_minib3d_TFormedZ"
TFormNormal%(x#,y#,z#,src_ent:TEntity,dest_ent:TEntity)="sidesign_minib3d_TFormNormal"
TFormPoint%(x#,y#,z#,src_ent:TEntity,dest_ent:TEntity)="sidesign_minib3d_TFormPoint"
TFormVector%(x#,y#,z#,src_ent:TEntity,dest_ent:TEntity)="sidesign_minib3d_TFormVector"
TranslateEntity%(ent:TEntity,x#,y#,z#,glob%=0)="sidesign_minib3d_TranslateEntity"
TriangleVertex%(surf:TSurface,tri_no%,corner%)="sidesign_minib3d_TriangleVertex"
TurnEntity%(ent:TEntity,x#,y#,z#,glob%=0)="sidesign_minib3d_TurnEntity"
UpdateNormals%(mesh:TMesh)="sidesign_minib3d_UpdateNormals"
UpdateWorld%(anim_speed#=1#)="sidesign_minib3d_UpdateWorld"
VectorPitch#(vx#,vy#,vz#)="sidesign_minib3d_VectorPitch"
VectorYaw#(vx#,vy#,vz#)="sidesign_minib3d_VectorYaw"
VertexAlpha#(surf:TSurface,vid%)="sidesign_minib3d_VertexAlpha"
VertexBlue#(surf:TSurface,vid%)="sidesign_minib3d_VertexBlue"
VertexColor%(surf:TSurface,vid%,r#,g#,b#,a#=1#)="sidesign_minib3d_VertexColor"
VertexCoords%(surf:TSurface,vid%,x#,y#,z#)="sidesign_minib3d_VertexCoords"
VertexGreen#(surf:TSurface,vid%)="sidesign_minib3d_VertexGreen"
VertexNormal%(surf:TSurface,vid%,nx#,ny#,nz#)="sidesign_minib3d_VertexNormal"
VertexNX#(surf:TSurface,vid%)="sidesign_minib3d_VertexNX"
VertexNY#(surf:TSurface,vid%)="sidesign_minib3d_VertexNY"
VertexNZ#(surf:TSurface,vid%)="sidesign_minib3d_VertexNZ"
VertexRed#(surf:TSurface,vid%)="sidesign_minib3d_VertexRed"
VertexTexCoords%(surf:TSurface,vid%,u#,v#,w#=0#,coord_set%=0)="sidesign_minib3d_VertexTexCoords"
VertexU#(surf:TSurface,vid%,coord_set%=0)="sidesign_minib3d_VertexU"
VertexV#(surf:TSurface,vid%,coord_set%=0)="sidesign_minib3d_VertexV"
VertexW#(surf:TSurface,vid%,coord_set%=0)="sidesign_minib3d_VertexW"
VertexX#(surf:TSurface,vid%)="sidesign_minib3d_VertexX"
VertexY#(surf:TSurface,vid%)="sidesign_minib3d_VertexY"
VertexZ#(surf:TSurface,vid%)="sidesign_minib3d_VertexZ"
Wireframe%(enable%)="sidesign_minib3d_Wireframe"
Text%(x%,y%,str$)="sidesign_minib3d_Text"
BeginMax2D%()="sidesign_minib3d_BeginMax2D"
EndMax2D%()="sidesign_minib3d_EndMax2D"
EntityScaleX#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityScaleX"
EntityScaleY#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityScaleY"
EntityScaleZ#(ent:TEntity,glob%=0)="sidesign_minib3d_EntityScaleZ"
LightMesh%(mesh:TMesh,red#,green#,blue#,range#=0#,light_x#=0#,light_y#=0#,light_z#=0#)="sidesign_minib3d_LightMesh"
MeshesIntersect%(mesh1:TMesh,mesh2:TMesh)="sidesign_minib3d_MeshesIntersect"
CreatePlane%(sub_divs%=1,parent:TEntity="bbNullObject")="sidesign_minib3d_CreatePlane"
AlignToVector%(vx#,vy#,vz#,axis%,rate%=1)="sidesign_minib3d_AlignToVector"
LoadAnimSeq%(ent:TEntity,filename$)="sidesign_minib3d_LoadAnimSeq"
SetAnimKey%(ent:TEntity,frame%,pos_key%=1,rot_key%=1,scale_key%=1)="sidesign_minib3d_SetAnimKey"
AddAnimSeq%(ent:TEntity,length%)="sidesign_minib3d_AddAnimSeq"
C_UpdateNormals%(no_tris%,no_verts%,tris@@*,vert_coords#*,vert_norms#*)="C_UpdateNormals"
C_NewMeshInfo@*()="C_NewMeshInfo"
C_DeleteMeshInfo%(mesh_info@*)="C_DeleteMeshInfo"
C_AddSurface%(mesh_info@*,no_tris%,no_verts%,tris@@*,verts#*,surf%)="C_AddSurface"
C_CreateColTree@*(mesh_info@*)="C_CreateColTree"
C_DeleteColTree%(col_tree@*)="C_DeleteColTree"
C_CreateCollisionInfoObject@*(vec_a@*,vec_b@*,vec_radius@*)="C_CreateCollisionInfoObject"
C_UpdateCollisionInfoObject%(col_info@*,dst_radius#,ax#,ay#,az#,bx#,by#,bz#)="C_UpdateCollisionInfoObject"
C_DeleteCollisionInfoObject%(col_info@*)="C_DeleteCollisionInfoObject"
C_CreateCollisionObject@*()="C_CreateCollisionObject"
C_DeleteCollisionObject%(coll@*)="C_DeleteCollisionObject"
C_Pick%(col_info@*,line@*,radius#,coll@*,dst_tform@*,mesh_col@*,pick_geom%)="C_Pick"
C_CollisionDetect%(col_info@*,coll@*,tform@*,col_tree@*,method_no%)="C_CollisionDetect"
C_CollisionResponse%(col_info@*,coll@*,response%)="C_CollisionResponse"
C_CollisionFinal%(col_info@*)="C_CollisionFinal"
C_CollisionPosX#()="C_CollisionPosX"
C_CollisionPosY#()="C_CollisionPosY"
C_CollisionPosZ#()="C_CollisionPosZ"
C_CollisionX#()="C_CollisionX"
C_CollisionY#()="C_CollisionY"
C_CollisionZ#()="C_CollisionZ"
C_CollisionNX#()="C_CollisionNX"
C_CollisionNY#()="C_CollisionNY"
C_CollisionNZ#()="C_CollisionNZ"
C_CollisionTime#()="C_CollisionTime"
C_CollisionSurface%()="C_CollisionSurface"
C_CollisionTriangle%()="C_CollisionTriangle"
C_CreateVecObject@*(x#,y#,z#)="C_CreateVecObject"
C_DeleteVecObject%(v@*)="C_DeleteVecObject"
C_UpdateVecObject%(vec@*,x#,y#,z#)="C_UpdateVecObject"
C_VecX#(vec@*)="C_VecX"
C_VecY#(vec@*)="C_VecY"
C_VecZ#(vec@*)="C_VecZ"
C_CreateLineObject@*(ox#,oy#,oz#,dx#,dy#,dz#)="C_CreateLineObject"
C_DeleteLineObject%(line@*)="C_DeleteLineObject"
C_UpdateLineObject%(line@*,ox#,oy#,oz#,dx#,dy#,dz#)="C_UpdateLineObject"
C_CreateMatrixObject@*(vec_i@*,vec_j@*,vec_k@*)="C_CreateMatrixObject"
C_DeleteMatrixObject%(mat@*)="C_DeleteMatrixObject"
C_UpdateMatrixObject%(mat@*,vec_i@*,vec_j@*,vec_k@*)="C_UpdateMatrixObject"
C_CreateTFormObject@*(mat@*,vec_v@*)="C_CreateTFormObject"
C_DeleteTFormObject%(tform@*)="C_DeleteTFormObject"
C_UpdateTFormObject%(tform@*,mat@*,vec_v@*)="C_UpdateTFormObject"
USE_MAX2D%=1
USE_VBO%=1
VBO_MIN_TRIS%=250
LOG_NEW%=0
LOG_DEL%=0
